DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
    SAMPLER: MyDomainSampler
  TRAIN_U:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 8

DATASET:
  NUM_SHOTS: 3

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 3e-3
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  WEIGHT_DECAY: 5e-4
  MOMENTUM: 0.9

TRAIN:
  PRINT_FREQ: 10

TEST:
  NO_TEST: False

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  NAME: "VAMP"
  VAMP:
    PREC: "fp16"
    CTX_INIT: "a photo of a"
    N_CTX: 16
    PROMPT_DEPTH: 12
    ALPHA1: 0.1
    ALPHA2: 0.01
    SIGMA: 1.0
    TSD: True
    TCC: True
    DDA: True
    SHARED_PROJ: False
    CONFI: 0.8