INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "random_translation", "normalize"]

DATASET:
  NAME: "MS_DomainNet"
  SOURCE_DOMAINS: []
  TARGET_DOMAINS: []
  DOMAINs: ["clipart", "painting", "real", "sketch"]